require:
  - rubocop-performance

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.3
  DisabledByDefault: true
  Exclude:
    - "examples/instrumentation.rb"
    - "gemfiles/**/*"

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Layout/LineLength:
  Max: 120

Lint:
  Enabled: true

Naming:
  Enabled: true
  Exclude:
    - "lib/rack/attack/path_normalizer.rb"

Performance:
  Enabled: true

Security:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  IgnoredMethods: [] # Workaround rubocop bug: https://github.com/rubocop-hq/rubocop/issues/6179

Style/BracesAroundHashParameters:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true
  Exclude:
    - "spec/**/*"

Style/ConditionalAssignment:
  Enabled: true

Style/Encoding:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: true

Style/EmptyMethod:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/OptionalArguments:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/RaiseArgs:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantPercentQ:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true
